{% set name = "pycron" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b916044e3e8253d5409c68df3ac64a3472c4e608dab92f40e8f595e5d3acb3de

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pycron

about:
  home: https://github.com/kipe/pycron
  license: MIT
  license_family: MIT
  # PR to add license_file to source dist: https://github.com/kipe/pycron/pull/17
  license_file: LICENSE
  summary: 'Simple cron-like parser, which determines if current datetime matches conditions.'
  dev_url: https://github.com/kipe/pycron

extra:
  recipe-maintainers:
    - synapticarbors
