travis:
  secure:
    BINSTAR_TOKEN: eYkNv7b/fBYkqp2vfXhEUGutfjmmgvNg88ecHUVkLzwajWvb3aRA09lKlOapp9XxnXsOoJCDkQmispe8uOs9x07EzOOkOYdBJh3c8uvlPqytyVOPC55lwmJR1Z8RNnwXUGvYbCC4VU1TV7hFVF6Q+t058girOvudpNjb4DDKgGu1C5Z45W5iR9YvoxV8rWVTxmLFlG/GseJE0SI18h0vcS7n95sSPL1uOPHuD/cg/+Hm6LxmPddkfzI9LWSaK0kg2zEGCWoypSduC+tdTSxxRQpycmdOiAe/KytfQZ8CUnOyjHl51fn68WIk6byW8qyj76K/Guq7zgFDdW3Mkbm0CHv8WrREzuWtmjY/WFhEEmWvjONAyV8QyngM0HdFM6ujQ8Kv/s846SdKMKKU8I5zYkVJp0/hQnrF160NwGYPVyy2HyJAPVcOwqblazKufGuD/4hKawhxllWYnpDHdaSrG6pMe9p1P5drgH6PPvb+YaVuvs7+pTEaSASOLVe0M+cqMCYV+urCa111kYi6Pu+pJ6PEf22q/bTF5/mjcl1cryjLohLCDFq6BEe2y8d59g0bJmbicFLooLar0wzXDq9iTugb3Dvnmiz+D12RWz3MMQtIQIlm9mBhc36N4GVuyoU+vMukRndHOhd7xBM/IX0wMtz+mXyt2PgrChlHB0/gthw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
